-- Pure SQL query to evaluate daily.raw_requisition_entry_list and load as new table rfm_check
CREATE OR REPLACE TABLE rfm_check AS
WITH reference_map AS (
    SELECT item_category, keyword FROM (VALUES
        ('Solar', 'Fuel'),
        ('Tire DT', 'Tire'),
        ('Tire ADT', 'Tire'),
        ('Tire VB', 'Tire'),
        ('Tire FT/ST', 'Tire'),
        ('Tire MG', 'Tire'),
        ('Tire Innova', 'Tire'),
        ('Oli dan Grease', 'Oli'),
        ('Seragam', 'Seragam'),
        ('APD', 'Safety'),
        ('Spare Part DT HANVAN XCMG', 'A2B'),
        ('Spare Part WL LW500FN XCMG', 'A2B'),
        ('Spare Part EXC - Komatsu', 'A2B'),
        ('Spare Part FT - Canter', 'A2B'),
        ('Stone Crusher dan Part', 'Crusher'),
        ('Generator dan Part', 'Genset'),
        ('Tower Light dan Part', '_TL'),
        ('Mesin Bor dan Part', 'Bor'),
        ('Spare Part DT - Fuso', 'A2B'),
        ('Safety Sign/Alat', 'Safety'),
        ('Lab Chemicals', 'Chem'),
        ('ATK', 'ATK'),
        ('ATK', 'GA'),
        ('Spare Part EXC - Volvo', 'A2B'),
        ('Container dan Part', 'Contain'),
        ('Spare Part WL - SDLG', 'A2B'),
        ('Spare Part EXC - SANY', 'A2B'),
        ('Tire WL', 'Tire'),
        ('Tire LT', 'Tire'),
        ('Spare Part Innova', 'LV'),
        ('Spare Part LV - Triton', 'LV'),
        ('Spare Part LV - Hilux', 'LV'),
        ('Lab Peralatan', 'Lab_Alat'),
        ('Jasa/Service', 'Jasa'),
        ('Jasa Logistik', 'Log'),
        ('Jasa Logistik', 'Kirim'),
        ('Spare Part ADT XDA40 XCMG', 'A2B'),
        ('Spare Part DZ - Komatsu', 'A2B'),
        ('Tire Manhaul', 'Tire'),
        ('Spare Part Manhaul - Isuzu', 'LV'),
        ('Kendaraan', 'Kendaraan'),
        ('Aksesoris Kendaraan', 'Kendaraan'),
        ('Spare Part LT - Dutro', 'LV'),
        ('Mesin Epsilon dan Part', 'Lab_Chem'),
        ('Makanan dan Minuman', 'Konsum'),
        ('Makanan dan Minuman', 'Mkn'),
        ('Tire LV', 'Tire'),
        ('Alat Reparasi Tire', 'Tire'),
        ('Aki/Accu', 'Aki'),
        ('Support Grease', 'Grease'),
        ('Spare Part VB - SANY', 'A2B'),
        ('Kontrak', 'Kontrak'),
        ('Cetak', 'Cetak'),
        ('Karoseri Manhaul', 'LV'),
        ('Karoseri LT', 'LV'),
        ('Karoseri FT', 'LV'),
        ('Spare Part Breaker - ZS', 'A2B'),
        ('Spare Part EXC 215C XCMG', 'A2B'),
        ('Spare Part EXC 370CA XCMG', 'A2B'),
        ('Spare Part EXC 490 XCMG', 'A2B'),
        ('Spare Part EXC 75DA XCMG', 'A2B'),
        ('Spare Part EXC 550 XCMG', 'A2B'),
        ('Spare Part DZ TY230 XCMG', 'A2B'),
        ('Spare Part DZ TSY230C XCMG', 'A2B'),
        ('Spare Part VB XS203J XCMG', 'A2B'),
        ('Spare Part VB XS113E XCMG', 'A2B'),
        ('Spare Part MG GR215 XCMG', 'A2B'),
        ('Spare Part MG GR2403 XCMG', 'A2B'),
        ('Spare Part MG GR2605 XCMG', 'A2B'),
        ('Spare Part FT NXG5250D2WC XCMG', 'A2B'),
        ('Spare Part FT XGA5250D2WC XCMG', 'A2B'),
        ('Spare Part FT NXG3250D2WCX XCMG', 'A2B'),
        ('Spare Part FT NXGA5250D2WCJY XCMG', 'A2B'),
        ('Spare Part EXC - Kobelco', 'A2B'),
        ('Radio HT, Rig', 'Radio'),
        ('Peralatan Survey', 'Survey'),
        ('Alat dan Bahan Bangunan', 'Bangunan'),
        ('Tools dan Alat Ukur', 'Tools'),
        ('Alat Teknik', 'Besi'),
        ('Besi dan Plat', 'Besi'),
        ('Furniture dan Elektronik', 'Furniture'),
        ('Alat Olahraga dan Hiburan', 'Furniture'),
        ('Perangkat IT', 'IT'),
        ('Telephone/HP', 'GA'),
        ('Alat Medic', 'Health'),
        ('Peralatan dan Aktivitas Enviro', 'HSE_Enviro'),
        ('Peralatan Shipping', 'Ship'),
        ('Seragam Security', 'Security'),
        ('Bolt dan Nut', 'Bolt'),
        ('Cat dan Peralatan Cat', 'Cat'),
        ('Consumable Workshop', 'ConsW'),
        ('Elektrikal', 'Elektrikal'),
        ('Pipa dan Fitting', 'Pipa'),
        ('Hose dan Crimping', 'Hose'),
        ('Peralatan Eksplor', 'EXPL_Alat'),
        ('Perabotan', 'RT/Dapur'),
        ('Perabotan', 'Perabot'),
        ('Peralatan Dapur', 'Dapur'),
        ('Packaging', 'Pack'),
        ('Consumable Cleaning', 'Clean'),
        ('Consumable Rumah Tangga', 'RT'),
        ('Refill/Gas', 'Gas'),
        ('Obat-Obatan', 'Obat'),
        ('Peralatan Geologi', 'Geo_Alat'),
        ('Spare Part LT - Canter', 'LV'),
        ('Spare Part Breaker - Volvo', 'A2B'),
        ('Tire TL', 'Tire'),
        ('Tire Forklift', 'Tire'),
        ('Spare Part LV - Dmax', 'LV'),
        ('Spare Part Forklift', 'LV'),
        ('Spare Part Vibro - XCMG', 'A2B'),
        ('Spare Part Vibro - SANY', 'A2B'),
        ('Spare Part Vibro - SAKAI', 'A2B'),
        ('TEST', 'Test'),
        ('Spare Part MG - Komatsu', 'A2B'),
        ('Spare Part Vibro - Bomag', 'A2B'),
        ('Spare Part Hiace', 'LV'),
        ('Tire Hiace', 'Tire'),
        ('Spare Part MG - CAT 140', 'A2B'),
        ('Aksesoris Alat Berat', 'A2B'),
        ('Petty Cash', 'Petty')
    ) AS ref(item_category, keyword)
),
checked_data AS (
    SELECT 
        r.*,
        string_agg(ref.keyword, ', ') AS expected_keywords,
        COALESCE(bool_or(contains(lower(COALESCE(CAST(r."Project" AS VARCHAR), '')), lower(ref.keyword))), false) AS is_category_project_match,
        CASE 
            WHEN count(ref.keyword) = 0 THEN 'UNKNOWN_CATEGORY'
            WHEN bool_or(contains(lower(COALESCE(CAST(r."Project" AS VARCHAR), '')), lower(ref.keyword))) THEN 'MATCH'
            ELSE 'MISMATCH'
        END AS match_status
    FROM daily.raw_requisition_entry_list r
    LEFT JOIN reference_map ref 
        ON lower(trim(COALESCE(CAST(r."Item Category" AS VARCHAR), ''))) = lower(trim(ref.item_category))
    GROUP BY ALL
)
SELECT * FROM checked_data;
